Made one step which determines if a feature branch on a fork should be used, or whether origin/master should be used

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -71,42 +71,40 @@ jobs:
       - name: Collect environment context variables
         shell: bash
         run: |
-          echo "::set-env name=REPO_BRANCH::${GITHUB_REF#refs/heads/}"
-          echo "::set-env name=REPO_USER::${GITHUB_REPOSITORY%/*}"
+          repo=maven-integration-testing
+          user=${GITHUB_REPOSITORY%/*}
+          branch=${GITHUB_REF#refs/heads/}
+          git ls-remote https://github.com/$user/$repo.git | grep $GITHUB_REF > /dev/null
+          if [ $? -eq 0 ]; then
+            echo "Using branch \"$branch\" in fork \"$user/$repo\"."
+            echo "::set-env name=REPO_BRANCH::$branch"
+            echo "::set-env name=REPO_USER::$user"
+          else
+            echo "Could not find fork \"$user/$repo\" or branch \"$branch\" in fork. Falling back to \"master\" in \"apache/$repo\"."
+            echo "::set-env name=REPO_BRANCH::master"
+            echo "::set-env name=REPO_USER::apache"
+          fi
 
-      - name: Checkout feature branch on the forked maven-integration-testing repo
+      - name: Checkout maven-integration-testing
         uses: actions/checkout@v2
         with:
           repository: ${{ env.REPO_USER }}/maven-integration-testing
           path: maven-integration-testing/
           ref: ${{ env.REPO_BRANCH }}
 
-      - name: Checkout master branch on the apache/maven-integration-testing repo
-        uses: actions/checkout@v2
-        if: failure()
-        with:
-          repository: apache/maven-integration-testing
-          path: maven-integration-testing/
-
-# TODO - split up integration test setup from the actual build
-
       - name: Download built Maven
         uses: actions/download-artifact@v2
-        if: always()
         with:
           name: built-maven
           path: built-maven/
 
 # TODO - Remove
       - name: debug ls
-        if: always()
         run: ls -laSh built-maven/
 
 # TODO - Remove
       - name: debug ls
-        if: always()
         run: ls -laSh $GITHUB_WORKSPACE
 
       - name: Running integration tests
-        if: always()
         run: mvn install -e -B -V -Prun-its,embedded -Dmaven.repo.local=$GITHUB_WORKSPACE/repo/ -DmavenDistro="$GITHUB_WORKSPACE/built-maven/apache-maven-bin.zip" -DwrapperDistroDir="$GITHUB_WORKSPACE/built-maven/" -f maven-integration-testing/pom.xml
